version: '3.9'
services:
  client:
    build: client
    ports:
      - '3000:3000'
  database:
    build: database
    ports:
      - '4002:4002'
  event-bus:
    build: event-bus
    ports:
      - '4000:4000'
  posts:
    build: posts
    ports:
      - '4001:4001'
  request-counter:
    build: request-counter
    ports:
      - '4003:4003'